# Generated by Django 3.1.4 on 2021-04-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='core_skill_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='core_skill_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='core_skill_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
